### PR TITLE
fix(MooLite): Configurable Plugin Width

### LINKED ISSUE #92: [Feature]: Configurable Plugin Width
As a developer I would like to control the width of my plugins UI.

Currently, we set MooLite to a fixed width when there is an active plugin tab. Instead, the width should be decided within each plugin. The current width could be set as the default, but a developer should be able to override the value. This could be in the form of a developer defined class string or a MooLite defined enum.

### PR DESCRIPTION
**Pull request by AS-Laguna**
To add this feature I did the following:

- Gave the `MooLiteTab` interface an optional width property.
- Moved the width decision logic from the base div to the plugin tab div.
- Added the default width to the PluginManagerDisplay tag.

Closes #92

### CODE REVIEW

**Comment by LagunaElectric** [comment]
Nice! Just learned about [template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) in typescript to ensure the developer uses a valid tailwind class.

**Review by Ishadijcks — CHANGES_REQUESTED** [review]

**Comment by Ishadijcks** [comment]
Looks nice, small remarks

**Comment by LagunaElectric** [comment]
Done :D

**Review by Ishadijcks — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
